[package]
name = "home-consule"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
axum = "0.2.5"
hyper = "0.14.13"
tower-http = { version = "0.1", features = ["fs"] }
rs-consul = "0.2.0"
structopt = "0.3.23"
handlebars = "4.1.3"
serde = "1.0"
